In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [11]:
# Configuration pour de meilleurs graphiques
plt.style.use('seaborn-v0_8-whitegrid')
sns.set_palette("Set2")
plt.rcParams['figure.figsize'] = (12, 8)
plt.rcParams['font.size'] = 12

In [12]:
# Chemin du projet et du fichier
project_root = r'C:\Users\Marouane\ImmoPredict'

# Lister tous les fichiers dans le dossier raw pour trouver le fichier DVF 2024
raw_dir = os.path.join(project_root, 'data', 'raw')
print("Fichiers disponibles dans le dossier raw:")
for file in os.listdir(raw_dir):
    print(f" - {file}")

Fichiers disponibles dans le dossier raw:
 - ValeursFoncieres-2024.txt

In [13]:
dvf_file = "valeursfoncieres-2024.txt"  
dvf_path = os.path.join(raw_dir, dvf_file)

In [14]:
if os.path.exists(dvf_path):
    print(f"\nLe fichier {dvf_file} existe!")
    print(f"Taille du fichier: {os.path.getsize(dvf_path) / (1024*1024):.2f} MB")
    
    # Chargement d'un petit échantillon pour explorer la structure
    try:
        # Essayer de lire les premières lignes pour comprendre la structure
        sample_df = pd.read_csv(dvf_path, sep='|', encoding='utf-8', nrows=5)
        print("\nAperçu des premières lignes:")
        display(sample_df.head())
        
        # Chargement d'un échantillon plus grand pour l'analyse
        print("\nChargement d'un échantillon plus grand pour l'analyse...")
        df_sample = pd.read_csv(dvf_path, sep='|', encoding='utf-8', nrows=50000)
        
        # Informations sur le dataset
        print("\nInformations sur le dataset:")
        print(f"Dimensions: {df_sample.shape}")
        print("\nTypes de données:")
        display(df_sample.dtypes)
        
        # Statistiques descriptives
        print("\nStatistiques descriptives:")
        display(df_sample.describe())
        
        # Vérification des valeurs manquantes
        print("\nValeurs manquantes par colonne:")
        missing_values = df_sample.isnull().sum()
        missing_percent = (missing_values / len(df_sample)) * 100
        missing_df = pd.DataFrame({'Nombre': missing_values, 'Pourcentage (%)': missing_percent})
        display(missing_df[missing_df['Nombre'] > 0].sort_values('Pourcentage (%)', ascending=False))
        
    except Exception as e:
        print(f"Erreur lors de la lecture du fichier: {e}")
        print("Essayons avec un encodage différent...")
        
        # Essayer avec un encodage différent si nécessaire
        try:
            sample_df = pd.read_csv(dvf_path, sep='|', encoding='latin1', nrows=5)
            print("\nAperçu des premières lignes (encodage latin1):")
            display(sample_df.head())
            
            # Si ça fonctionne, utiliser cet encodage pour l'échantillon complet
            df_sample = pd.read_csv(dvf_path, sep='|', encoding='latin1', nrows=50000)
            print(f"Dimensions: {df_sample.shape}")
        except Exception as e2:
            print(f"Nouvelle erreur: {e2}")
else:
    print(f"\nLe fichier {dvf_path} n'existe pas!")
    print("Veuillez vérifier le nom exact du fichier et son emplacement.")

Le fichier valeursfoncieres-2024.txt existe!
Taille du fichier: 439.92 MB

Aperçu des premières lignes:

,Identifiant de document,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,Date mutation,Nature mutation,...,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,02/01/2024,Vente,...,NaN,0,NaN,NaN,NaN,NaN,NaN,P,NaN,99.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,03/01/2024,Vente,...,NaN,0,NaN,NaN,NaN,NaN,NaN,S,NaN,115.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,08/01/2024,Vente,...,NaN,0,NaN,NaN,NaN,NaN,NaN,S,NaN,497.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,03/01/2024,Vente,...,NaN,1,3.0,Dépendance,NaN,0.0,0.0,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,03/01/2024,Vente,...,NaN,2,3.0,Dépendance,NaN,0.0,0.0,NaN,NaN,NaN

Chargement d'un échantillon plus grand pour l'analyse...

Informations sur le dataset:
Dimensions: (50000, 43)

Types de données:

C:\Users\Marouane\AppData\Local\Temp\ipykernel_8348\3381633263.py:14: DtypeWarning: Columns (24,29,31,33) have mixed types. Specify dtype option on import or set low_memory=False.
  df_sample = pd.read_csv(dvf_path, sep='|', encoding='utf-8', nrows=50000)

Identifiant de document       float64
Reference document            float64
1 Articles CGI                float64
2 Articles CGI                float64
3 Articles CGI                float64
4 Articles CGI                float64
5 Articles CGI                float64
No disposition                  int64
Date mutation                  object
Nature mutation                object
Valeur fonciere                object
No voie                       float64
B/T/Q                          object
Type de voie                   object
Code voie                      object
Voie                           object
Code postal                   float64
Commune                        object
Code departement                int64
Code commune                    int64
Prefixe de section            float64
Section                        object
No plan                         int64
No Volume                     float64
1er lot                        object
Surface Carrez du 1er lot      object
2eme lot                      float64
Surface Carrez du 2eme lot     object
3eme lot                      float64
Surface Carrez du 3eme lot     object
4eme lot                      float64
Surface Carrez du 4eme lot     object
5eme lot                      float64
Surface Carrez du 5eme lot     object
Nombre de lots                  int64
Code type local               float64
Type local                     object
Identifiant local             float64
Surface reelle bati           float64
Nombre pieces principales     float64
Nature culture                 object
Nature culture speciale        object
Surface terrain               float64
dtype: object

Statistiques descriptives:

,Identifiant de document,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,No voie,Code postal,...,2eme lot,3eme lot,4eme lot,5eme lot,Nombre de lots,Code type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Surface terrain
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50000.000000,23261.000000,49833.000000,...,2986.000000,717.000000,219.000000,54.000000,50000.000000,22915.000000,0.0,22829.000000,22829.000000,39611.000000
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.093640,684.021495,1573.312082,...,105.865037,90.108787,63.894977,50.592593,0.281300,2.245778,NaN,87.219326,1.855797,2778.740552
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.365286,1771.221786,494.585751,...,270.743399,268.973690,121.989370,83.753799,0.720237,0.973055,NaN,1801.919743,2.168794,11912.465921
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1000.000000,...,2.000000,2.000000,2.000000,2.000000,0.000000,1.000000,NaN,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,14.000000,1210.000000,...,9.000000,6.000000,6.000000,6.250000,0.000000,1.000000,NaN,0.000000,0.000000,230.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,52.000000,1390.000000,...,38.000000,21.000000,9.000000,9.000000,0.000000,3.000000,NaN,38.000000,0.000000,656.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,258.000000,1800.000000,...,92.000000,76.000000,61.000000,62.250000,0.000000,3.000000,NaN,92.000000,4.000000,1620.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,9731.000000,2880.000000,...,4122.000000,3040.000000,552.000000,358.000000,57.000000,4.000000,NaN,265000.000000,20.000000,734066.000000

Valeurs manquantes par colonne:

                            Nombre  Pourcentage (%)
Identifiant de document      50000          100.000
Reference document           50000          100.000
1 Articles CGI               50000          100.000
2 Articles CGI               50000          100.000
3 Articles CGI               50000          100.000
4 Articles CGI               50000          100.000
5 Articles CGI               50000          100.000
Identifiant local            50000          100.000
Surface Carrez du 5eme lot   49993           99.986
Surface Carrez du 4eme lot   49955           99.910
5eme lot                     49946           99.892
No Volume                    49887           99.774
Surface Carrez du 3eme lot   49830           99.660
4eme lot                     49781           99.562
3eme lot                     49283           98.566
Surface Carrez du 2eme lot   48919           97.838
Nature culture speciale      48771           97.542
B/T/Q                        48542           97.084
Prefixe de section           48000           96.000
Surface Carrez du 1er lot    47588           95.176
2eme lot                     47014           94.028
1er lot                      40033           80.066
Type de voie                 27268           54.536
Nombre pieces principales    27171           54.342
Surface reelle bati          27171           54.342
Code type local              27085           54.170
Type local                   27085           54.170
No voie                      26739           53.478
Nature culture               10389           20.778
Surface terrain              10389           20.778
Valeur fonciere                543            1.086
Voie                           167            0.334
Code postal                    167            0.334
Code voie                      167            0.334